cesga/2020 unloaded
        Preparing the environment for use of the CESGA 2020 software stack.
        Please rebuild modules cache: module --ignore-cache avail
     
cesga/2020 loaded
python/3.9.9 loaded
jupyter-server/1.13.5-python-3.9.9 loaded
jupyterlab/3.2.4-python-3.9.9 loaded
Traceback (most recent call last):
  File "/mnt/netapp2/Home_FT2/home/usc/ec/rsm/fivesegmentor/./code/training/run_benchmark.py", line 292, in <module>
    train_and_evaluate(name_model, dataset, config, logging_enabled=logging_enabled)
  File "/mnt/netapp2/Home_FT2/home/usc/ec/rsm/fivesegmentor/./code/training/run_benchmark.py", line 93, in train_and_evaluate
    model: torch.nn.Module = models[model_name]().to(device)
  File "/mnt/netapp2/Home_FT2/home/usc/ec/rsm/fivesegmentor/./code/training/run_benchmark.py", line 76, in <lambda>
    models[name] = lambda: RoiNet(
  File "/mnt/netapp2/Home_FT2/home/usc/ec/rsm/fivesegmentor/code/models/roinet.py", line 26, in __init__
    self.dict_module.add_module(f"conv{i}", cls_conv_block(ch1, ch2, k_size=k_size, layer_num=i))
TypeError: __init__() got an unexpected keyword argument 'k_size'
srun: error: a100-33: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=10280658.0
