cesga/2020 unloaded
        Preparing the environment for use of the CESGA 2020 software stack.
        Please rebuild modules cache: module --ignore-cache avail
     
cesga/2020 loaded
python/3.9.9 loaded
jupyter-server/1.13.5-python-3.9.9 loaded
jupyterlab/3.2.4-python-3.9.9 loaded
Traceback (most recent call last):
  File "/mnt/netapp2/Store_uni/home/usc/ec/rsm/fivesegmentor/code/training/run_benchmark.py", line 453, in <module>
    all_datasets = prepare_datasets_from_json(args.config, args.model, augmentation_config, restormer_config=args.restormer)
  File "/mnt/netapp2/Store_uni/home/usc/ec/rsm/fivesegmentor/code/ds/dataset.py", line 123, in prepare_datasets_from_json
    "val": SegmentationDataset(paths["val"],
  File "/mnt/netapp2/Store_uni/home/usc/ec/rsm/fivesegmentor/code/ds/dataset.py", line 214, in __init__
    raise ValueError("Error: No valid images found in dataset.")
ValueError: Error: No valid images found in dataset.
